### ISSUE TITLE
Create playground plug-in

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra-playground-plugin#2]
**Context**
Create a playground plugin which will be started by Thyra.  The plugin is an Http api written in go.

**Needs** 
Simulator must be included in this version of the playground. IE: the back-end must be able to execute the simulator with provided config by the playground front-end.

**Comment by peterjah** [comment]
>>>>>>>>>>>>>>> /!\ Read this before merge<<<<<<<<<
When the playground PR will be merged, i have to update the submodule commit in the PR with the new commit on main branch from playground
