### ISSUE TITLE
Use github release to produce binaries

### ISSUE THREAD

**Issue by peterjah** [massalabs/thyra-playground-plugin#4]
To facilitate the use of plugins in Thyra, we need to automatize the packaging+upload of the plugin.

This issue is about thyra playground plugin but we should be able to reuse this for other plugins

Whats is already done?:
- packaging for Linux and MacOs and windows wich produces workflow artifact (which is a zip archive)

what we want:

- use github release upload instead of workflow artifact.
the issue with workflow artifact is to be forced to use zip archive which lead to the loss of file permission (annoying especially for executables)
The idea is to use tar for linux/mac and 7z for windows to package the plugin.
Inspiration can be found here: 
https://github.com/massalabs/massa-sc-tester/blob/main/.github/workflows/cd.yml

**Comment by SlnPons** [comment]
@longgamma-massa what is the status of the playground product please ? 
Is that fair to delete or ignore it completely (ie: not to maintain it until further notice)?
